[project]
name = "machine-learning-hyperparameter-tuning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lightgbm>=4.6.0",
    "scikit-learn>=1.8.0",
    "streamlit>=1.52.2",
    "xgboost>=3.1.2",
]
